#!/bin/bash
# my_processes

process=$(ps u | grep $USER | wc -l)
#                       test $process -gt $1 means $process > $1
if test $process -gt $1
then
    echo "More than $1 user processes active"
else
    echo "Equal or less than $1 processes active"
fi
